planningShool/routes/web.php
<?php

use Illuminate\Support\Facades\Auth;
use Illuminate\Support\Facades\Route;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

/*Route::get('/', function () {
    return view('welcome');
});*/
Route::get('/', [App\Http\Controllers\WelcomeController::class, 'welcome']);
Auth::routes();
Route::get('/voirToutUser', [App\Http\Controllers\WelcomeController::class, 'voirToutUser'])->name('voirToutUser');
Route::get('/home', [App\Http\Controllers\HomeController::class, 'index'])->name('home');
//Route::get('loadLevels/{$id}', 'App\Http\Controllers\TimeTableController@selectedCourse')->name('loadLevels');
Route::get('createTTStep2', 'App\Http\Controllers\TimeTableController@createStep2')->name('createTTStep2');
Route::post('selectedUE', 'App\Http\Controllers\TimeTableController@selectedUE');
Route::post('selectedGroup', 'App\Http\Controllers\TimeTableController@selectedGroup');
Route::post('saveCours', 'App\Http\Controllers\TimeTableController@saveCours');
Route::post('searchSpec', 'App\Http\Controllers\TimeTableController@searchSpec');
Route::post('delEx', 'App\Http\Controllers\TimeTableController@delEx');

Route::get('displayTTStud', 'App\Http\Controllers\TimeTableController@displayTTStud')->name('displayTTStud');
Route::get('displayTTEns', 'App\Http\Controllers\TimeTableController@displayTTEns')->name('displayTTEns');
Route::get('displayTTHall', 'App\Http\Controllers\TimeTableController@displayTTHall')->name('displayTTHall');
Route::get('displayCompleteTT', 'App\Http\Controllers\TimeTableController@displayCompleteTT')->name('displayCompleteTT');


Route::get('/connectStudent','App\Http\Controllers\TimeTableController@connectStudent')->name('connectStudent');
Route::get('/connectTeacher', 'App\Http\Controllers\TimeTableController@connectTeacher')->name('connectTeacher');
Route::group(['prefix' => 'timeTable', 'middleware' => ['auth'], 'namespace' => 'App\Http\Controllers', 'as' => 'TimeTable.'], function() {
    Route::resource('timetable', 'TimeTableController');

});
Route::group(['prefix' => 'EnsFil', 'middleware' => ['auth'], 'namespace' => 'App\Http\Controllers', 'as' => 'EnsFil.'], function() {
    Route::resource('EF', 'EnseignantFiliereController');

});
//CRUD CLASSE
Route::get('/liste/classe', [App\Http\Controllers\classeController::class, 'classe'])->name('classe.liste');
Route::get('/classe/create', [App\Http\Controllers\classeController::class, 'create'])->name('classe.create');
Route::get('/classe/{classe}', [App\Http\Controllers\classeController::class, 'edite'])->name('classe.edite');
Route::post('/classe/create', [App\Http\Controllers\classeController::class, 'ajouter'])->name('classe.ajouter');
Route::delete('/classe/{classe}', [App\Http\Controllers\classeController::class, 'supprimer'])->name('classe.supprimer');
Route::put('/classe/{classe}', [App\Http\Controllers\classeController::class, 'update'])->name('classe.update');
//CRUD UE

Route::get('/liste/ue', [App\Http\Controllers\ueController::class, 'ue'])->name('ue.liste');
Route::get('/ue/create', [App\Http\Controllers\ueController::class, 'create'])->name('ue.create');
Route::post('/ue/create', [App\Http\Controllers\ueController::class, 'ajouter'])->name('ue.ajouter');
Route::delete('/ue/{ue} ', [App\Http\Controllers\ueController::class, 'supprimer'])->name('ue.supprimer');
Route::get('/ue/{ue} ', [App\Http\Controllers\ueController::class, 'edite'])->name('ue.edite');
Route::put('/ue/{ue} ', [App\Http\Controllers\ueController::class, 'update'])->name('ue.update');

//Groupe
Route::get('groupe/create/{groupe}/{classe} ', [App\Http\Controllers\groupeController::class, 'edite'])->name('groupe.edite');
Route::put('groupe/create/{groupe}/{classe} ', [App\Http\Controllers\groupeController::class, 'update'])->name('groupe.update');
Route::get('liste/groupe/{classe}' , [App\Http\Controllers\groupeController::class, 'groupe'])->name('groupe.liste');
Route::get('groupe/create/{classe} ', [App\Http\Controllers\groupeController::class, 'create'])->name('groupe.create');
Route::post('groupe/create ', [App\Http\Controllers\groupeController::class, 'ajouter'])->name('groupe.ajouter');
Route::delete('groupe/create/{groupe}', [App\Http\Controllers\groupeController::class, 'supprimer'])->name('groupe.supprimer');
Route::resource('timetable', 'TimeTableController');




Route::group(['prefix' => 'admin', 'middleware' => ['auth'], 'namespace' => 'App\Http\Controllers\admin', 'as' => 'admin.'], function() {
    Route::resource('niveau', 'NiveauCOntroller');
    Route::resource('specialites', 'SpecialiteController');
    Route::resource('filiere', 'FiliereController');
    Route::resource('enseignant', 'EnseignantController');
    Route::resource('salle', 'SalleController');
});
Route::get('voirEnsFil', 'App\Http\Controllers\admin\FiliereController@voirEnsFil')->name('voirEnsFil');
Route::get('delEnsFil', 'App\Http\Controllers\admin\FiliereController@delEnsFil')->name('delEnsFil');

planningShool/app/Models/Filiere.php
<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Factories\HasFactory;
use Illuminate\Database\Eloquent\Model;

class Filiere extends Model
{
    use HasFactory;
    protected $fillable = [
        'nom_filiere'
    ];
}

planningShool/app/Http/Controllers/admin/FiliereController.php
<?php

namespace App\Http\Controllers\admin;
use Illuminate\Support\Facades\DB;
use App\Http\Controllers\Controller;
use App\Models\Filiere;
use App\Models\EnseignantsFilieres;
use Illuminate\Http\Request;
use Brian2694\Toastr\Facades\Toastr;

class FiliereController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        $filieres = Filiere::all();
        return view('admin.filiere.index', compact('filieres'));
    }
    
    public function voirEnsFil(Request $request)
    {
        $ens= DB::table('enseignants_filieres')
        ->where('enseignants_filieres.id_filiere',$request->filiere)
        ->join('enseignants', 'enseignants.id', '=', 'enseignants_filieres.id_enseignant')
     
         ->select('enseignants_filieres.id as id_EF','enseignants.*','enseignants_filieres.*' )        
        ->get();
        return view('admin/filiere/voirEnsFil', ['ens'=>$ens]);
    }
    public function delEnsFil(Request $request)
    {
        $ens= EnseignantsFilieres::
      where('id',$request->id)
     ->delete();
        return back();
    }
    
    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        return view('admin.filiere.create');
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
        try {
            Filiere::create([
                'nom_filiere' => $request->input('nom_filiere'),
                
            ]);
            Toastr::success('messages', trans('success'));
            return back();
        } catch(\Exception $e) {
            Toastr::error('message', trans('erreur'));
            return back();
        }
    }

    /**
     * Display the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function show($id)
    {
        //
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function edit($id)
    {
        try {
            $filiere = Filiere::findOrFail($id);
            return view('admin.filiere.edit', compact('filiere'));
        } catch(\Exception $e) {
            Toastr::error('message', trans('failed to load'));
            return back();
        }
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, $id)
    {
        try {
            Filiere::where('id', $id)->update([
                'nom_filiere' => $request->input('nom_filiere'),
            ]);
            Toastr::success('messages', trans('success'));
            return back();
        } catch(\Exception $e) {
            Toastr::error('messages', trans('erreur'));
            return back();
        }
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function destroy($id)
    {
        try
        {
            $filiere = Filiere::findOrFail($id);
            $filiere->delete();
            Toastr::success('messages', trans('success'));
            return back();
        }catch(\Exception $e){
            Toastr::error('message', trans('erreur de supression'));
            return back();
        }
    }
}

planningShool/resources/views/admin/filiere/create.blade.php
@section('title')

@endsection
@extends('layouts.layout')

@section('content')

  <!-- Content Header (Page header) -->
  <section class="content-header">
    <div class="container-fluid">
      <div class="row mb-2">
        <div class="col-sm-12">
          <h1>Ajouter une filière</h1>
        </div>
        <div class="col-sm-12">
          <ol class="breadcrumb float-sm-right">
            <li class="breadcrumb-item"><a href="/">Home</a></li>
            <li class="breadcrumb-item"><a href="{{ route('admin.filiere.index') }}">Liste filieres</a></li>
            <li class="breadcrumb-item active">Filières</li>
          </ol>
        </div>
      </div>
    </div><!-- /.container-fluid -->
  </section>

  <!-- Main content -->
  <section class="content">
    <div class="container-fluid">
      <div class="row">
        <div class="col-md-12">
            <!-- general form elements -->
            <div class="card card-primary">
              <div class="card-header">
                <h3 class="card-title">Ajouter une filière</h3>
              </div>
              <!-- /.card-header -->
              <!-- form start -->
              <form action="{{ route('admin.filiere.store') }}" method="POST">
                @csrf
                <div class="card-body">
                  
                  <div class="form-group">
                    <label for="exampleInputEmail1">nom de la filière</label>
                    <input type="text" class="form-control" id="exampleInputEmail1"  name="nom_filiere" placeholder="entrer une filiere" required>
                  </div>
                  
                </div>
                <div class="card-footer">
                  <button type="submit" class="btn btn-outline-success">valider</button>
                </div>
              </form>
            </div>
            <!-- /.card -->
          </div>

      </div>
      <!-- /.row -->
    </div>
    <!-- /.container-fluid -->
  </section>
  <!-- /.content -->
  @endsection

  @section('scripts')
  <script>
    $(function () {
      $("#example1").DataTable({
        "responsive": true, "lengthChange": false, "autoWidth": false,
        "buttons": ["copy", "csv", "excel", "pdf", "print", "colvis"]
      }).buttons().container().appendTo('#example1_wrapper .col-md-6:eq(0)');
      $('#example2').DataTable({
        "paging": true,
        "lengthChange": false,
        "searching": false,
        "ordering": true,
        "info": true,
        "autoWidth": false,
        "responsive": true,
      });
    });
  </script>
  @endsection

planningShool/resources/views/admin/filiere/edit.blade.php
@section('title')

@endsection
@extends('layouts.layout')

@section('content')

  <!-- Content Header (Page header) -->
  <section class="content-header">
    <div class="container-fluid">
      <div class="row mb-2">
        <div class="col-sm-6">
          <h1>Modifier une Filière</h1>
        </div>
        <div class="col-sm-6">
          <ol class="breadcrumb float-sm-right">
            <li class="breadcrumb-item"><a href="/">Home</a></li>
            <li class="breadcrumb-item"><a href="{{ route('admin.filiere.index') }}">Liste filières</a></li>

            <li class="breadcrumb-item active">Filière</li>
          </ol>
        </div>
      </div>
    </div><!-- /.container-fluid -->
  </section>

  <!-- Main content -->
  <section class="content">
    <div class="container-fluid">
      <div class="row">
        <div class="col-md-6">
            <!-- general form elements -->
            <div class="card card-primary">
              <div class="card-header">
                <h3 class="card-title">Modifier une Filière</h3>
              </div>
              <!-- /.card-header -->
              <!-- form start -->
              <form action="{{ route('admin.filiere.update', $filiere->id) }}" method="POST">
                @csrf
                @method('PUT')
                <div class="card-body">
                  <div class="form-group">
                    <label>Filiere</label>
                    <input type="text" class="form-control"  value={{ $filiere->nom_filiere }}  name="nom_filiere" placeholder="entrer une filiere" required>
                  </div>
                  <div class="form-group">
                    <label>Code de la Filiere</label>
                    <input type="text" class="form-control"  value={{ $filiere->code_filiere }}  name="code_filiere" placeholder="entrer le code de la filiere" required>
                  </div>
                </div>
                <div class="card-footer">
                  <button type="submit" class="btn btn-outline-success">valider</button>
                </div>
              </form>
            </div>
            <!-- /.card -->
          </div>

      </div>
      <!-- /.row -->
    </div>
    <!-- /.container-fluid -->
  </section>
  <!-- /.content -->
  @endsection

  @section('scripts')
  <script>
    $(function () {
      $("#example1").DataTable({
        "responsive": true, "lengthChange": false, "autoWidth": false,
        "buttons": ["copy", "csv", "excel", "pdf", "print", "colvis"]
      }).buttons().container().appendTo('#example1_wrapper .col-md-6:eq(0)');
      $('#example2').DataTable({
        "paging": true,
        "lengthChange": false,
        "searching": false,
        "ordering": true,
        "info": true,
        "autoWidth": false,
        "responsive": true,
      });
    });
  </script>
  @endsection

planningShool/resources/views/admin/filiere/index.blade.php
@section('title')

@endsection
@extends('layouts.layout')

@section('content')

  <!-- Content Header (Page header) -->
  <section class="content-header">
    <div class="container-fluid">
      <div class="row mb-2">
        <div class="col-sm-12">
          <h1>Listes Des Filières</h1>
        </div>
        <div class="col-sm-12">
          <ol class="breadcrumb float-sm-right">
            <li class="breadcrumb-item"><a href="/">Home</a></li>
            <li class="breadcrumb-item active">Filières</li>
          </ol>
        </div>
      </div>
    </div><!-- /.container-fluid -->
  </section>

  <!-- Main content -->
  <section class="content">
    <div class="container-fluid">
      <div class="row">
        <div class="col-12">
          <div class="card">
            <div class="card-header">
              <h3 class="card-title">Ici est affiché la liste des filières de l'établissement</h3>
              <div class="float-right">
                <a href="{{ route('admin.filiere.create') }}" class="btn btn-primary">Ajouter</a>
            </div>
            </div>
            <!-- /.card-header -->
            <div class="card-body">
              <table id="example1" class="table table-bordered table-striped">
                <thead>
                <tr>
                  <th>Nom de la filière</th>
                  <th>Action</th>
                </tr>
                </thead>
                <tbody>
                    @foreach($filieres as $filiere)
                        <tr>
                            <td>{{$filiere->nom_filiere}}</td>
                            <td>
                          
                                <a class="btn btn-outline-danger" href="{{ route('admin.filiere.edit', $filiere->id) }}" title="edit">
                                    <i class="fas fa-edit"></i>
                                </a>
                                <a class="btn btn-outline-danger" href="" onclick="event.preventDefault();
                                            document.getElementById('delete-form').submit();" title="delete">
                                    <i class="fas fa-trash-alt"></i>
                                </a>

                                <form id="delete-form" action="{{ route('admin.filiere.destroy', $filiere->id) }}" method="POST" class="d-none">
                                    @csrf
                                    @method('DELETE')
                                </form>
                                <a  href="{{ route('voirEnsFil', ['filiere'=>$filiere->id]) }}" class="btn btn-xs btn-primary" >
                                    voir les enseignants de la filiere
                                </a>
                            </td>
                        </tr>
                    @endforeach
                </tbody>
                <tfoot>
                
                </tfoot>
              </table>
            </div>
            <!-- /.card-body -->
          </div>
          <!-- /.card -->
        </div>
        <!-- /.col -->


        
      <!-- /.row -->
    </div>
    <!-- /.container-fluid -->
  </section>
  <!-- /.content -->
  @endsection

  @section('scripts')
  <script>
    $(function () {
      $("#example1").DataTable({
        "responsive": true, "lengthChange": false, "autoWidth": false,
        "buttons": ["copy", "csv", "excel", "pdf", "print", "colvis"]
      }).buttons().container().appendTo('#example1_wrapper .col-md-6:eq(0)');
      $('#example2').DataTable({
        "paging": true,
        "lengthChange": false,
        "searching": false,
        "ordering": true,
        "info": true,
        "autoWidth": false,
        "responsive": true,
      });
    });
  </script>
  @endsection

planningShool/resources/views/admin/filiere/voirEnsFil.blade.php
@section('title')

@endsection
@extends('layouts.layout')

@section('content')

  <!-- Content Header (Page header) -->
  <section class="content-header">
    <div class="container-fluid">
      <div class="row mb-2">
        <div class="col-sm-12">
          <h1>Listes Des Filières</h1>
        </div>
        <div class="col-sm-12">
          <ol class="breadcrumb float-sm-right">
            <li class="breadcrumb-item"><a href="/">Home</a></li>
            <li class="breadcrumb-item active">Filières</li>
          </ol>
        </div>
      </div>
    </div><!-- /.container-fluid -->
  </section>

  <!-- Main content -->
  <section class="content">
    <div class="container-fluid">
      <div class="row">
        <div class="col-12">
          <div class="card">
            <div class="card-header">
              <h3 class="card-title">Ici est affiché la liste des filières de l'établissement</h3>
              <div class="float-right">
                <a href="{{ route('admin.filiere.create') }}" class="btn btn-primary">Ajouter</a>
            </div>
            </div>
            <!-- /.card-header -->
            <div class="card-body">
              <table id="example1" class="table table-bordered table-striped">
                <thead>
                <tr>
                  <th>Nom prenom enseignant</th>
                  <th>Action</th>
                </tr>
                </thead>
                <tbody>
                    @foreach($ens as $e)
                        <tr>
                            <td>{{$e->titre}} {{$e->nom_enseignant}} {{$e->prenom_enseignant}}</td>
                            <td>
                          
                                <a class="btn btn-outline-danger" href="{{ route('delEnsFil', ['id'=>$e->id_EF]) }}" title="edit">
                                    <i class="fas fa-trash-alt"></i>
                                </a>
                               
                            </td>
                        </tr>
                    @endforeach
                </tbody>
                <tfoot>
                
                </tfoot>
              </table>
            </div>
            <!-- /.card-body -->
          </div>
          <!-- /.card -->
        </div>
        <!-- /.col -->


        
      <!-- /.row -->
    </div>
    <!-- /.container-fluid -->
  </section>
  <!-- /.content -->
  @endsection

  @section('scripts')
  <script>
    $(function () {
      $("#example1").DataTable({
        "responsive": true, "lengthChange": false, "autoWidth": false,
        "buttons": ["copy", "csv", "excel", "pdf", "print", "colvis"]
      }).buttons().container().appendTo('#example1_wrapper .col-md-6:eq(0)');
      $('#example2').DataTable({
        "paging": true,
        "lengthChange": false,
        "searching": false,
        "ordering": true,
        "info": true,
        "autoWidth": false,
        "responsive": true,
      });
    });
  </script>
  @endsection