planningShool/routes/web.php
<?php

use Illuminate\Support\Facades\Auth;
use Illuminate\Support\Facades\Route;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

/*Route::get('/', function () {
    return view('welcome');
});*/
Route::get('/', [App\Http\Controllers\WelcomeController::class, 'welcome']);
Auth::routes();
Route::get('/voirToutUser', [App\Http\Controllers\WelcomeController::class, 'voirToutUser'])->name('voirToutUser');
Route::get('/home', [App\Http\Controllers\HomeController::class, 'index'])->name('home');
//Route::get('loadLevels/{$id}', 'App\Http\Controllers\TimeTableController@selectedCourse')->name('loadLevels');
Route::get('createTTStep2', 'App\Http\Controllers\TimeTableController@createStep2')->name('createTTStep2');
Route::post('selectedUE', 'App\Http\Controllers\TimeTableController@selectedUE');
Route::post('selectedGroup', 'App\Http\Controllers\TimeTableController@selectedGroup');
Route::post('saveCours', 'App\Http\Controllers\TimeTableController@saveCours');
Route::post('searchSpec', 'App\Http\Controllers\TimeTableController@searchSpec');
Route::post('delEx', 'App\Http\Controllers\TimeTableController@delEx');

Route::get('displayTTStud', 'App\Http\Controllers\TimeTableController@displayTTStud')->name('displayTTStud');
Route::get('displayTTEns', 'App\Http\Controllers\TimeTableController@displayTTEns')->name('displayTTEns');
Route::get('displayTTHall', 'App\Http\Controllers\TimeTableController@displayTTHall')->name('displayTTHall');
Route::get('displayCompleteTT', 'App\Http\Controllers\TimeTableController@displayCompleteTT')->name('displayCompleteTT');


Route::get('/connectStudent','App\Http\Controllers\TimeTableController@connectStudent')->name('connectStudent');
Route::get('/connectTeacher', 'App\Http\Controllers\TimeTableController@connectTeacher')->name('connectTeacher');
Route::group(['prefix' => 'timeTable', 'middleware' => ['auth'], 'namespace' => 'App\Http\Controllers', 'as' => 'TimeTable.'], function() {
    Route::resource('timetable', 'TimeTableController');

});
Route::group(['prefix' => 'EnsFil', 'middleware' => ['auth'], 'namespace' => 'App\Http\Controllers', 'as' => 'EnsFil.'], function() {
    Route::resource('EF', 'EnseignantFiliereController');

});
//CRUD CLASSE
Route::get('/liste/classe', [App\Http\Controllers\classeController::class, 'classe'])->name('classe.liste');
Route::get('/classe/create', [App\Http\Controllers\classeController::class, 'create'])->name('classe.create');
Route::get('/classe/{classe}', [App\Http\Controllers\classeController::class, 'edite'])->name('classe.edite');
Route::post('/classe/create', [App\Http\Controllers\classeController::class, 'ajouter'])->name('classe.ajouter');
Route::delete('/classe/{classe}', [App\Http\Controllers\classeController::class, 'supprimer'])->name('classe.supprimer');
Route::put('/classe/{classe}', [App\Http\Controllers\classeController::class, 'update'])->name('classe.update');
//CRUD UE

Route::get('/liste/ue', [App\Http\Controllers\ueController::class, 'ue'])->name('ue.liste');
Route::get('/ue/create', [App\Http\Controllers\ueController::class, 'create'])->name('ue.create');
Route::post('/ue/create', [App\Http\Controllers\ueController::class, 'ajouter'])->name('ue.ajouter');
Route::delete('/ue/{ue} ', [App\Http\Controllers\ueController::class, 'supprimer'])->name('ue.supprimer');
Route::get('/ue/{ue} ', [App\Http\Controllers\ueController::class, 'edite'])->name('ue.edite');
Route::put('/ue/{ue} ', [App\Http\Controllers\ueController::class, 'update'])->name('ue.update');

//Groupe
Route::get('groupe/create/{groupe}/{classe} ', [App\Http\Controllers\groupeController::class, 'edite'])->name('groupe.edite');
Route::put('groupe/create/{groupe}/{classe} ', [App\Http\Controllers\groupeController::class, 'update'])->name('groupe.update');
Route::get('liste/groupe/{classe}' , [App\Http\Controllers\groupeController::class, 'groupe'])->name('groupe.liste');
Route::get('groupe/create/{classe} ', [App\Http\Controllers\groupeController::class, 'create'])->name('groupe.create');
Route::post('groupe/create ', [App\Http\Controllers\groupeController::class, 'ajouter'])->name('groupe.ajouter');
Route::delete('groupe/create/{groupe}', [App\Http\Controllers\groupeController::class, 'supprimer'])->name('groupe.supprimer');
Route::resource('timetable', 'TimeTableController');




Route::group(['prefix' => 'admin', 'middleware' => ['auth'], 'namespace' => 'App\Http\Controllers\admin', 'as' => 'admin.'], function() {
    Route::resource('niveau', 'NiveauCOntroller');
    Route::resource('specialites', 'SpecialiteController');
    Route::resource('filiere', 'FiliereController');
    Route::resource('enseignant', 'EnseignantController');
    Route::resource('salle', 'SalleController');
});
Route::get('voirEnsFil', 'App\Http\Controllers\admin\FiliereController@voirEnsFil')->name('voirEnsFil');
Route::get('delEnsFil', 'App\Http\Controllers\admin\FiliereController@delEnsFil')->name('delEnsFil');

planningShool/app/Models/Enseignant.php
<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Factories\HasFactory;
use Illuminate\Database\Eloquent\Model;

class Enseignant extends Model
{
    use HasFactory;
    protected $fillable = [
        'matricule','titre','nom_enseignant','prenom_enseignant','telephone','email','adresse'
    ];
}

planningShool/app/Http/Controllers/admin/EnseignantController.php
<?php

namespace App\Http\Controllers\admin;

use App\Http\Controllers\Controller;
use Illuminate\Http\Request;
use App\Models\Enseignant;
use Brian2694\Toastr\Facades\Toastr;

class EnseignantController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        $enseignants = Enseignant::all();
        return view('admin.enseignant.index', compact('enseignants'));
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        return view('admin.enseignant.create');
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
        try {
            Enseignant::create([
                'matricule' => $request->input('matricule'),
                'titre' => $request->input('titre'),
                'nom_enseignant' => $request->input('nom_enseignant'),
                'prenom_enseignant' => $request->input('prenom_enseignant'),
                'telephone' => $request->input('telephone'),
                'email' => $request->input('email'),
                'adresse' => $request->input('adresse'),

            ]);
            Toastr::success('messages', trans('success'));
            return back();
        } catch(\Exception $e) {
            Toastr::error('message', trans('erreur'));
            return back();
        }
    }

    /**
     * Display the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function show($id)
    {
        //
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function edit($id)
    {
        try {
            $enseignant = Enseignant::findOrFail($id);
            return view('admin.enseignant.edit', compact('enseignant'));
        } catch(\Exception $e) {
            Toastr::error('message', trans('failed to load'));
            return back();
        }
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, $id)
    {
        try {
            Enseignant::where('id', $id)->update([
                'matricule' => $request->input('matricule'),
                'titre' => $request->input('titre'),
                'nom_enseignant' => $request->input('nom_enseignant'),
                'prenom_enseignant' => $request->input('prenom_enseignant'),
                'telephone' => $request->input('telephone'),
                'email' => $request->input('email'),
                'adresse' => $request->input('adresse'),
            ]);
            Toastr::success('messages', trans('success'));
            return back();
        } catch(\Exception $e) {
            Toastr::error('messages', trans('erreur'));
            return back();
        }
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function destroy($id)
    {
        try
        {
            $enseignant = Enseignant::findOrFail($id);
            $enseignant->delete();
            Toastr::success('messages', trans('success'));
            return back();
        }catch(\Exception $e){
            Toastr::error('message', trans('erreur de supression'));
            return back();
        }
    }
}

planningShool/resources/views/admin/enseignant/create.blade.php
@section('title')

@endsection
@extends('layouts.layout')

@section('content')

  <!-- Content Header (Page header) -->
  <section class="content-header">
    <div class="container-fluid">
      <div class="row mb-2">
        <div class="col-sm-12">
          <h1>Ajouter un enseignant</h1>
        </div>
        <div class="col-sm-12">
          <ol class="breadcrumb float-sm-right">
            <li class="breadcrumb-item"><a href="/">Home</a></li>
            <li class="breadcrumb-item"><a href="{{ route('admin.enseignant.index') }}">Liste enseignant</a></li>
            <li class="breadcrumb-item active">Enseignant</li>
            
          </ol>
        </div>
      </div>
    </div><!-- /.container-fluid -->
  </section>

  <!-- Main content -->
  <section class="content">
    <div class="container-fluid">
      <div class="row">
        <div class="col-md-12">
            <!-- general form elements -->
            <div class="card card-primary">
              <div class="card-header">
                <h3 class="card-title">Ajouter un enseignant</h3>
              </div>
              <!-- /.card-header -->
              <!-- form start -->
              <form action="{{ route('admin.enseignant.store') }}" method="POST">
                @csrf
                <div class="card-body">
                  <div class="form-group">
                    <label for="exampleInputEmail1">Matricule de l'enseignant </label>
                    <input type="text" class="form-control" id="exampleInputEmail1"  name="matricule" placeholder="entrer le matricule de l'enseignant" required>
                  </div>
                  <div class="form-group">
                    <label for="exampleInputEmail1">Titre de l'enseignant</label>
                    <input type="text" class="form-control" id="exampleInputEmail1"  name="titre" placeholder="entrer le titre de l'enseignant" required>
                  </div>
                  <div class="form-group">
                    <label for="exampleInputEmail1">Nom de l'enseignant </label>
                    <input type="text" class="form-control" id="exampleInputEmail1"  name="nom_enseignant" placeholder="entrer le nom de l'enseignant" required>
                  </div>
                  <div class="form-group">
                    <label for="exampleInputEmail1">Prenom de l'enseignant</label>
                    <input type="text" class="form-control" id="exampleInputEmail1"  name="prenom_enseignant" placeholder="entrer le prenom de l'enseignant" required>
                  </div>
                  <div class="form-group">
                    <label for="exampleInputEmail1">Telephone de l'enseignant</label>
                    <input type="number" class="form-control" id="exampleInputEmail1"  name="telephone" placeholder="entrer le numero  de l'enseignant" required>
                  </div>
                  <div class="form-group">
                    <label for="exampleInputEmail1">Email de l'enseignant</label>
                    <input type="email" class="form-control" id="exampleInputEmail1"  name="email" placeholder="entrer l'email de l'enseignant" required>
                  </div>
                  <div class="form-group">
                    <label for="exampleInputEmail1">Adresse de l'enseignant</label>
                    <input type="text" class="form-control" id="exampleInputEmail1"  name="adresse" placeholder="entrer le prenom de l'enseignant" required>
                  </div>
                  
                </div>
                <div class="card-footer">
                  <button type="submit" class="btn btn-outline-success">valider</button>
                </div>
              </form>
            </div>
            <!-- /.card -->
          </div>

      </div>
      <!-- /.row -->
    </div>
    <!-- /.container-fluid -->
  </section>
  <!-- /.content -->
  @endsection

  @section('scripts')
  <script>
    $(function () {
      $("#example1").DataTable({
        "responsive": true, "lengthChange": false, "autoWidth": false,
        "buttons": ["copy", "csv", "excel", "pdf", "print", "colvis"]
      }).buttons().container().appendTo('#example1_wrapper .col-md-6:eq(0)');
      $('#example2').DataTable({
        "paging": true,
        "lengthChange": false,
        "searching": false,
        "ordering": true,
        "info": true,
        "autoWidth": false,
        "responsive": true,
      });
    });
  </script>
  @endsection

planningShool/resources/views/admin/enseignant/edit.blade.php
@section('title')

@endsection
@extends('layouts.layout')

@section('content')

  <!-- Content Header (Page header) -->
  <section class="content-header">
    <div class="container-fluid">
      <div class="row mb-2">
        <div class="col-sm-12">
          <h1>Modifier les informations d'un enseignant</h1>
        </div>
        <div class="col-sm-12">
          <ol class="breadcrumb float-sm-right">
            <li class="breadcrumb-item"><a href="/">Home</a></li>
            <li class="breadcrumb-item"><a href="{{ route('admin.enseignant.index') }}">Liste enseignant</a></li>
            <li class="breadcrumb-item active">Enseignant</li>
          </ol>
        </div>
      </div>
    </div><!-- /.container-fluid -->
  </section>

  <!-- Main content -->
  <section class="content">
    <div class="container-fluid">
      <div class="row">
        <div class="col-md-12">
            <!-- general form elements -->
            <div class="card card-primary">
              <div class="card-header">
                <h3 class="card-title">Modifier une information</h3>
              </div>
              <!-- /.card-header -->
              <!-- form start -->
              <form action="{{ route('admin.enseignant.update', $enseignant->id) }}" method="POST">
                @csrf
                @method('PUT')
                <div class="card-body">
                <div class="form-group">
                    <label>Matricule de l'enseignant</label>
                    <input type="text" class="form-control"  value={{ $enseignant->matricule }}  name="matricule" placeholder="entrer le matricule d'un enseignant" required>
                  </div>
                  <div class="form-group">
                    <label>Titre de l'enseignant</label>
                    <input type="text" class="form-control"  value={{ $enseignant->titre }}  name="titre" placeholder="entrer le titre de la enseignant" required>
                  </div>
                  <div class="form-group">
                    <label>Nom de l'enseignant</label>
                    <input type="text" class="form-control"  value={{ $enseignant->nom_enseignant }}  name="nom_enseignant" placeholder="entrer un enseignant" required>
                  </div>
                  <div class="form-group">
                    <label>Prenom de l'enseignant</label>
                    <input type="text" class="form-control"  value={{ $enseignant->prenom_enseignant }}  name="prenom_enseignant" placeholder="entrer le code de la enseignant" required>
                  </div>
                  <div class="form-group">
                    <label>Numero de téléphone de l'enseignant</label>
                    <input type="text" class="form-control"  value={{ $enseignant->telephone }}  name="telephone" placeholder="entrer de telephone d'un enseignant" required>
                  </div>
                  <div class="form-group">
                    <label>Email de l'enseignant</label>
                    <input type="email" class="form-control"  value={{ $enseignant->email }}  name="email" placeholder="entrer l'email de enseignant" require>
                  </div>
                  <div class="form-group">
                    <label>Adresse de l'enseignant</label>
                    <input type="text" class="form-control"  value={{ $enseignant->adresse }}  name="adresse" placeholder="entrer l'adresse de enseignant" require>
                  </div>
                </div>
                <div class="card-footer">
                  <button type="submit" class="btn btn-outline-success">valider</button>
                </div>
                
              </form>
            </div>
            <!-- /.card -->
          </div>

      </div>
      <!-- /.row -->
    </div>
    <!-- /.container-fluid -->
  </section>
  <!-- /.content -->
  @endsection

  @section('scripts')
  <script>
    $(function () {
      $("#example1").DataTable({
        "responsive": true, "lengthChange": false, "autoWidth": false,
        "buttons": ["copy", "csv", "excel", "pdf", "print", "colvis"]
      }).buttons().container().appendTo('#example1_wrapper .col-md-6:eq(0)');
      $('#example2').DataTable({
        "paging": true,
        "lengthChange": false,
        "searching": false,
        "ordering": true,
        "info": true,
        "autoWidth": false,
        "responsive": true,
      });
    });
  </script>
  @endsection

planningShool/resources/views/admin/enseignant/index.blade.php
@section('title')

@endsection
@extends('layouts.layout')

@section('content')

  <!-- Content Header (Page header) -->
  <section class="content-header">
    <div class="container-fluid">
      <div class="row mb-2">
        <div class="col-sm-12">
          <h1>Listes Des Enseignants</h1>
        </div>
        <div class="col-sm-12">
          <ol class="breadcrumb float-sm-right">
            <li class="breadcrumb-item"><a href="/">Home</a></li>
            <li class="breadcrumb-item active">Enseignant</li>
          </ol>
        </div>
      </div>
    </div><!-- /.container-fluid -->
  </section>

  <!-- Main content -->
  <section class="content">
    <div class="container-fluid">
      <div class="row">
        <div class="col-12">
          <div class="card">
            <div class="card-header">
              <h3 class="card-title">Ici est affiché la liste des enseignants de l'université</h3>
              <div class="float-right">
                <a href="{{ route('admin.enseignant.create') }}" class="btn btn-primary">Ajouter</a>
            </div>
            </div>
            <!-- /.card-header -->
            <div class="card-body">
              <table id="example1" class="table table-bordered table-striped">
                <thead>
                <tr>
                  <th>Matricule</th>
                  <th>Titre</th>
                  <th>Nom</th>
                  <th>Prenom</th>
                  <th>telephone</th>
                  <th>Email</th>
                  <th>Adresse</th>
                  <th>Action</th>
                </tr>
                </thead>
                <tbody>
                    @foreach($enseignants as $enseignant)
                        <tr>
                            <td>{{$enseignant->matricule}}</td>
                            <td>{{$enseignant->titre}}</td>
                            <td>{{$enseignant->nom_enseignant}}</td>
                            <td>{{$enseignant->prenom_enseignant}}</td>
                            <td>{{$enseignant->telephone}}</td>
                            <td>{{$enseignant->email}}</td>
                            <td>{{$enseignant->adresse}}</td>
                            <td>
                               
                                <a class="btn btn-outline-danger" href="{{ route('admin.enseignant.edit', $enseignant->id) }}" title="edit">
                                    <i class="fas fa-edit"></i>
                                </a>
                                <a class="btn btn-xs btn-primary" href="{{ route('displayTTEns', ['matricule'=>$enseignant->matricule, 'nom'=>$enseignant->nom_enseignant]) }}" >
                                   voir son emploie de temps
                                </a>
                                <a class="btn btn-outline-danger" href="" onclick="event.preventDefault();
                                            document.getElementById('delete-form').submit();" title="delete">
                                    <i class="fas fa-trash-alt"></i>
                                </a>

                                <form id="delete-form" action="{{ route('admin.enseignant.destroy', $enseignant->id) }}" method="POST" class="d-none">
                                    @csrf
                                    @method('DELETE')
                                </form>
                            </td>
                        </tr>
                    @endforeach
                </tbody>
                <tfoot>
                
                </tfoot>
              </table>
            </div>
            <!-- /.card-body -->
          </div>
          <!-- /.card -->
        </div>
        <!-- /.col -->


        
      <!-- /.row -->
    </div>
    <!-- /.container-fluid -->
  </section>
  <!-- /.content -->
  @endsection

  @section('scripts')
  <script>
    $(function () {
      $("#example1").DataTable({
        "responsive": true, "lengthChange": false, "autoWidth": false,
        "buttons": ["copy", "csv", "excel", "pdf", "print", "colvis"]
      }).buttons().container().appendTo('#example1_wrapper .col-md-6:eq(0)');
      $('#example2').DataTable({
        "paging": true,
        "lengthChange": false,
        "searching": false,
        "ordering": true,
        "info": true,
        "autoWidth": false,
        "responsive": true,
      });
    });
  </script>
  @endsection